### PR TITLE
Bug fix in models.py

### PR DESCRIPTION
**Pull request by mjag1898**
alphamold2_multimer_v3 is written as alphamold2_multimer_3 in line 27.

### CODE REVIEW

**Comment by milot-mirdita** [comment]
Thank you!

**Comment by sokrypton** [comment]
alphamold? 😛

**Comment by sokrypton** [comment]
whatever we just did broke alphafold:
https://github.com/sokrypton/ColabFold/issues/546

**Comment by milot-mirdita** [comment]
I think this fixed the problem

**Comment by sokrypton** [comment]
All working on my side.

**Pull request merged**
