### PR TITLE
Use path to stereo_chemical_props.txt relative to batch.py

### PR DESCRIPTION
**Pull request by jkosinski**
Otherwise, batch.py cannot find the file in some running scenarios.

### CODE REVIEW

**Comment by martin-steinegger** [comment]
Thank you so much. Could you please run `black` to fix the Lint error?

**Comment by jkosinski** [comment]
ok, done, now passes.

**Comment by martin-steinegger** [comment]
thank you! 👍

**Comment by jkosinski** [comment]
Actually, sorry, won't this commit break your interactive notebooks? Now I can see that in your interactive notebooks you download stereo_chemical_props.txt to the running directory... My edit reads from the directory of batch.py...

**Comment by martin-steinegger** [comment]
Yes, I reverted it.

**Pull request merged**
